apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: dot-2724
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dot-2724 
  name: dot-2724
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: dot-2724
    weight: 100 
